[2019-10-29 15:17:31,920] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: kims_flow.test_task 2019-10-28T00:00:00+00:00 [queued]>
[2019-10-29 15:17:31,930] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: kims_flow.test_task 2019-10-28T00:00:00+00:00 [queued]>
[2019-10-29 15:17:31,931] {taskinstance.py:841} INFO - 
--------------------------------------------------------------------------------
[2019-10-29 15:17:31,931] {taskinstance.py:842} INFO - Starting attempt 1 of 1
[2019-10-29 15:17:31,931] {taskinstance.py:843} INFO - 
--------------------------------------------------------------------------------
[2019-10-29 15:17:31,942] {taskinstance.py:862} INFO - Executing <Task(PythonOperator): test_task> on 2019-10-28T00:00:00+00:00
[2019-10-29 15:17:31,943] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'kims_flow', 'test_task', '2019-10-28T00:00:00+00:00', '--job_id', '12', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/kim_flow.py', '--cfg_path', '/var/folders/kl/hgsvczsx34q1wqd4l94kdxsh0000gn/T/tmp7w5h8f9z']
[2019-10-29 15:17:33,543] {base_task_runner.py:115} INFO - Job 12: Subtask test_task [2019-10-29 15:17:33,543] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-10-29 15:17:33,545] {base_task_runner.py:115} INFO - Job 12: Subtask test_task [2019-10-29 15:17:33,543] {dagbag.py:92} INFO - Filling up the DagBag from /Users/hyuninsim/airflow/dags/kim_flow.py
[2019-10-29 15:17:34,576] {base_task_runner.py:115} INFO - Job 12: Subtask test_task [2019-10-29 15:17:34,576] {cli.py:545} INFO - Running <TaskInstance: kims_flow.test_task 2019-10-28T00:00:00+00:00 [running]> on host ip-70-12-224-51.kscymo.spcsdns.net
[2019-10-29 15:17:34,594] {python_operator.py:105} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=kims_flow
AIRFLOW_CTX_TASK_ID=test_task
AIRFLOW_CTX_EXECUTION_DATE=2019-10-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-10-28T00:00:00+00:00
[2019-10-29 15:17:34,595] {taskinstance.py:1058} ERROR - test_module() got an unexpected keyword argument 'conf'
Traceback (most recent call last):
  File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: test_module() got an unexpected keyword argument 'conf'
[2019-10-29 15:17:34,603] {taskinstance.py:1089} INFO - Marking task as FAILED.
[2019-10-29 15:17:34,621] {base_task_runner.py:115} INFO - Job 12: Subtask test_task Traceback (most recent call last):
[2019-10-29 15:17:34,621] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/bin/airflow", line 37, in <module>
[2019-10-29 15:17:34,621] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     args.func(args)
[2019-10-29 15:17:34,621] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-29 15:17:34,621] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     return f(*args, **kwargs)
[2019-10-29 15:17:34,621] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 551, in run
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     _run(args, dag, ti)
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/bin/cli.py", line 469, in _run
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     pool=args.pool,
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     return func(*args, **kwargs)
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in _run_raw_task
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     result = task_copy.execute(context=context)
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
[2019-10-29 15:17:34,622] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     return_value = self.execute_callable()
[2019-10-29 15:17:34,623] {base_task_runner.py:115} INFO - Job 12: Subtask test_task   File "/Users/hyuninsim/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
[2019-10-29 15:17:34,623] {base_task_runner.py:115} INFO - Job 12: Subtask test_task     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-10-29 15:17:34,623] {base_task_runner.py:115} INFO - Job 12: Subtask test_task TypeError: test_module() got an unexpected keyword argument 'conf'
[2019-10-29 15:17:36,910] {logging_mixin.py:112} INFO - [2019-10-29 15:17:36,909] {local_task_job.py:124} WARNING - Time since last heartbeat(0.01 s) < heartrate(5.0 s), sleeping for 4.992972 s
[2019-10-29 15:17:41,910] {logging_mixin.py:112} INFO - [2019-10-29 15:17:41,905] {local_task_job.py:103} INFO - Task exited with return code 1
